version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres-contatos
    restart: always
    environment:
      POSTGRES_DB: contatos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: contatos-api
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_data:
